// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbpefewwvwnfbywusozf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icGVmZXd3dnduZmJ5d3Vzb3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODk1NDEsImV4cCI6MjA3MzM2NTU0MX0.GQ5sGdeTrP3N1TCKKVjSdgEjQuTyVfbg-ymiotkoMO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});